spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test01?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

logging:
  group:
    my: org.example
  level:
    my: debug

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
